// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYWTUPVZ0zlt66mBQuN0KtIxzOaCw4lFc',
    appId: '1:467960375056:web:d30fbeb04c59aae7646795',
    messagingSenderId: '467960375056',
    projectId: 'chat-541ca',
    authDomain: 'chat-541ca.firebaseapp.com',
    storageBucket: 'chat-541ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcnp0u5g4ApiaNFgHR5LZ1MxOXOqhao28',
    appId: '1:467960375056:android:87ee26723d6b349b646795',
    messagingSenderId: '467960375056',
    projectId: 'chat-541ca',
    storageBucket: 'chat-541ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDASE1V15xtgvnXs0AqalOC59G94OtJ1JE',
    appId: '1:467960375056:ios:a894e59d66b624da646795',
    messagingSenderId: '467960375056',
    projectId: 'chat-541ca',
    storageBucket: 'chat-541ca.appspot.com',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDASE1V15xtgvnXs0AqalOC59G94OtJ1JE',
    appId: '1:467960375056:ios:a894e59d66b624da646795',
    messagingSenderId: '467960375056',
    projectId: 'chat-541ca',
    storageBucket: 'chat-541ca.appspot.com',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYWTUPVZ0zlt66mBQuN0KtIxzOaCw4lFc',
    appId: '1:467960375056:web:663003ffce8fdd37646795',
    messagingSenderId: '467960375056',
    projectId: 'chat-541ca',
    authDomain: 'chat-541ca.firebaseapp.com',
    storageBucket: 'chat-541ca.appspot.com',
  );
}
